services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
    restart: unless-stopped  # Ensures the container restarts on crash or reboot
    deploy:                  # Optional: resource limits for production
      resources:
        limits:
          cpus: "0.5"        # Limit to 0.5 CPU cores
          memory: "512M"     # Limit to 512MB of memory